config/routes.rb
Rails.application.routes.draw do
  root to: 'quotations#new'
  resources :quotations, only: [:new, :create] do
    get 'thank_you'
    collection do
      post 'create_transaction'
      post 'create_callback'
      post 'create_card_info'
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :quotations, optional: true
  belongs_to :transaction_infos, optional: true

  # enum type: ["quotation_addr", "transaction_info_addr"]

  validates :address, :postal_code, :city, :province, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/callback_information.rb
class CallbackInformation < ApplicationRecord
  belongs_to :transaction_info, optional: true

  enum call_availabilities: ['AM', 'Between 11AM and 1PM', 'PM', 'Between 4PM and 6:30PM']
end

app/models/card_information.rb
class CardInformation < ApplicationRecord
  belongs_to :transaction_info
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  has_one :address
  accepts_nested_attributes_for :address
  
  has_many :transaction_info
  accepts_nested_attributes_for :transaction_info


  validates :first_name, :last_name, :email, :eval_value, :phone_number, presence: true
  validates_numericality_of :eval_value, :greater_than_or_equal_to => 0.0
  
  def calculate_insurance_premium(eval)
    prime_tx = ((((eval-500000)/1000)*1.17)+320)
    ((prime_tx.round(2) + 20 + (prime_tx*0.09).round(2)).abs).round(2)
  end
  

end

app/models/transaction_info.rb
class TransactionInfo < ApplicationRecord
  enum languages: [:english, :french]
  enum property_types: ['Single-family dwelling', 'Condominium', 'Undivided co-ownership', 'Duplex', 'Triplex', 'Quadruplex', '5 Units', '6 Units', 'Vacant property (no building)']

  has_one :address
  accepts_nested_attributes_for :address

  has_one :callback_information
  has_one :card_information

  belongs_to :quotation
  # validates :language, :home_owner_1, :property_type, :purchase_date, :lot_number, :bound_water, :muncipal_water, :insurance_issued, :insurance_denied, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController

  def new
    @quotation = Quotation.new
    @quotation.build_address
  end

  def create_transaction
    @transaction = TransactionInfo.new(transaction_params)
    respond_to do |format|
      if @transaction.save
        if params[:request_callback]
          @res_type = 'Callback'
          @callback_information = CallbackInformation.new
        else
          @res_type = 'Payment'
          @card_information = CardInformation.new
        end
        format.js { render layout: false }
      else
        format.js { render layout: false, status: :unprocessable_entity }
      end
    end
  end

  def thank_you
    @quotation = Quotation.includes(:address, transaction_info: [:address]).find_by(id: params[:quotation_id])
    @transaction = @quotation.transaction_info.last
    unless @quotation && @transaction
      redirect_to root_path
    end
  end
  

  def create_callback
    @callback_information = CallbackInformation.create(callback_params)
    redirect_to quotation_thank_you_path(quotation_id: @callback_information.transaction_info.quotation_id)
  end

  def create_card_info
    @card_information = CardInformation.create(card_info_params)
    redirect_to quotation_thank_you_path(quotation_id: @card_information.transaction_info.quotation_id)
  end
  
  
  def create
    @quotation = Quotation.new(quotation_params)
    @quotation.insurance_value = @quotation.calculate_insurance_premium(@quotation.eval_value)

    respond_to do |format|
      if @quotation.save
        @transaction = create_new_transaction(@quotation)
        format.js { render layout: false }
        format.html { redirect_to root_path, notice: "Quotation was successfully created." }      
      else
        format.js { render layout: false, status: :unprocessable_entity }
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

    def quotation_params
      params.require(:quotation).permit(:first_name, :last_name, :email, :eval_value, :phone_number, address_attributes: [:address, :postal_code, :city, :province])
    end

    def transaction_params
      params.require(:transaction_info).permit(:language, :quotation_id, :home_owner_1, :home_owner_2, :home_owner_3, :property_type, :purchase_date, :lot_number, :bound_water, :muncipal_water, :insurance_issued, :insurance_denied, :note, :agent_name, :agent_email, address_attributes: [:address, :postal_code, :city, :province])
    end

    def card_info_params
      params.require(:card_information).permit(:postal_code, :card_number, :expiry_date, :card_name, :transaction_info_id, :cvv, :email, :transaction_info_id)
    end

    def callback_params
      params.require(:callback_information).permit(:phone_number, :call_availability, :transaction_info_id)
    end

    def create_new_transaction(quotation)
      transaction = TransactionInfo.new
      transaction.home_owner_1 = quotation.first_name + ' ' + quotation.last_name
      transaction.build_address
      transaction.address = quotation.address
      transaction
    end
    
    
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InsuranceDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotations/_address_fields.html.erb
<div class="field">
  <%= f.label :address %>
  <%= f.text_area :address, required: true, class: 'w-100' %>
</div>

<div class="field">
  <%= f.label :postal_code %>
  <%= f.text_field :postal_code, required: true, class: 'w-100' %>
</div>

<div class="field">
  <%= f.label :city %>
  <%= f.text_field :city, required: true, class: 'w-100' %>
</div>

<div class="field">
  <%= f.label :province %>
  <%= f.text_field :province, required: true, class: 'w-100' %>
</div>

app/views/quotations/_callback_modal.html.erb
<div class="modal fade" id="callback_form" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" >Request Callback</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with(model: @callback_information, remote: true, url: create_callback_quotations_path) do |f| %>
          <div class="field row">
            <div class="col-4">
              <%= f.label :phone_number %>
            </div>
            <div class="col-4">
              <%= f.text_field :phone_number %>
            </div>
          </div>

          <div class="field row">
            <div class="col-4">
              <%= f.label 'Best moment to call you*' %>
            </div>
            <div class="col-4">
              <%= f.select :call_availability, CallbackInformation.call_availabilities.keys,required: true %>
            </div>
          </div>

          <%= f.hidden_field :transaction_info_id,value: @transaction.id %>
          <%= f.submit "Request callback", class: 'btn btn-primary'%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/quotations/_error.html.erb
<% if @quotation && @quotation.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@quotation.errors.count, "error") %> prohibited this quotation from being saved:</h2>

    <ul>
      <% @quotation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<% if @transaction && @transaction.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

    <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/quotations/_form.html.erb
<%= form_with(model: quotation, remote: true) do |form| %>
  <div id="error_fields">
  </div>
  <div class="row mx-0">
    <div class="col-6">
      <div class="field">
        <%= form.label 'First Name*' %>
        <%= form.text_field :first_name, required: true, class: 'w-100', class: 'w-100' %>
      </div>

      <div class="field">
        <%= form.label 'Last Name*' %>
        <%= form.text_field :last_name, required: true, class: 'w-100' %>
      </div>

      <div class="field">
        <%= form.label 'Phone Number*' %>
        <%= form.number_field :phone_number, required: true, class: 'w-100' %>
      </div>

      <div class="field">
        <%= form.label 'Email*' %>
        <%= form.email_field :email, required: true, class: 'w-100' %>
      </div>

      <div class="field">
        <%= form.label 'Muncipal Evaluation Of The Property*' %>
        <%= form.number_field :eval_value, required: true, class: 'w-100' %>
      </div>
    </div>

    <div class="col-6">
      <%= form.fields_for :address do |f| %>
        <%= render partial: "address_fields", locals: {f: f}%>
      <% end %>
    </div>

    <div class="actions">
      <%= form.submit "GET A QUOTE", class: 'btn btn-primary my-3' %>
    </div>
  </div>
<% end %>


<div id="transaction_form">
</div>

<div id="modal_form">
</div>

app/views/quotations/_payment_modal.html.erb
<div class="modal fade" id="card_info_form" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Pay Online</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with(model: @card_information, remote: true, url: create_card_info_quotations_path) do |f| %>
          <div class="field row">
            <div class="col-4">
              <%= f.label :postal_code %>
            </div>
            <div class="col-8">
              <%= f.text_field :postal_code,required: true %>
            </div>
          </div>

          <div class="field row">
            <div class="col-4">
              <%= f.label :card_name %>
            </div>
            <div class="col-8">
              <%= f.text_field :card_name,required: true %>
            </div>
          </div>

          <div class="field row">
            <div class="col-4">
              <%= f.label :card_number %>
            </div>
            <div class="col-8">
              <%= f.text_field :card_number,required: true %>
            </div>
          </div>

          <div class="field row">
            <div class="col-4">
              <%= f.label :expiry_date %>
            </div>
            <div class="col-8">
              <%= f.month_field :expiry_date,required: true, min: Date.today %>
            </div>
            <%= f.hidden_field :transaction_info_id,value: @transaction.id %>
          </div>

          <div class="field row">
            <div class="col-4">
              <%= f.label :cvv %>
            </div>
            <div class="col-8">
              <%= f.password_field :cvv,required: true, pattern: "[0-9]{3,4}", placeholder: 'CVV ***'  %>
            </div>
          </div>

          <div class="field row">
            <div class="col-4">
              <%= f.label :email %>
            </div>
            <div class="col-8">
              <%= f.text_field :email,required: true %>
            </div>
          </div>

          <%= f.submit "Pay $#{@transaction.quotation.insurance_value}", class: "btn btn-success" %>          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/quotations/_transaction_form.html.erb
<hr>
<div>
  <h2>INSURANCE PREMIUM</h2>
  <h1 class="text-primary"> <%= @quotation.insurance_value %> $ </h1>

  <h4> For a property valued at <%= @quotation.eval_value %>$ , your one time insurance premium is <%= @quotation.insurance_value %> </h4>
</div>
<hr>

<h2> Transaction Information </h2>
<%= form_with(model: @transaction, remote: true, url: create_transaction_quotations_path) do |f| %>
  <div id="transaction_error_fields">
  </div>

  <div class="field d-flex">
    <%= f.hidden_field :quotation_id, value: @quotation.id %>
    <%= f.label 'Languages:*' %>
    <div class='d-flex mx-3'>
      <% TransactionInfo.languages.each do |lang, val| %>
        <%= f.radio_button :language, val, required: true %>
        <%= f.label lang,class: 'mx-2',for: "transaction_info_language_#{val}" %>
      <% end %>
    </div>
  </div>

  <div class="field">
    <%= f.label 'Homeowner(s) Name(s)*' %>
    <%= f.text_field :home_owner_1, placeholder: 'Owner 1*', required: true %>
    <%= f.text_field :home_owner_2, placeholder: 'Owner 2' %>
    <%= f.text_field :home_owner_3, placeholder: 'Owner 3' %>
  </div>

  <div class="field">
    <%= f.label 'Property type*' %>
    <%= f.select :property_type, TransactionInfo.property_types.keys, :include_blank => 'Select Property Type',required: true %>
  </div>

  <div class="field">
    <%= f.label 'Property owner' %>
    <%= f.radio_button :property_owner, true %> Yes
  </div>

  <div class="field">
    <%= f.label 'Purchase date*' %>
    <%= f.date_field :purchase_date, max: Date.today,required: true %>
  </div>

  <hr>
  <h2> Legal info </h2>

  <div class="field">
    <%= f.label 'Lots number(s):*' %>
    <%= f.text_field :lot_number, required: true,placeholder: 'Lot Number*' %>
  </div>
  
  <div class="row mx-0">
    <div class="col-4 px-0">
      <%= f.fields_for :address do |f| %>
        <%= render partial: "address_fields", locals: {f: f}%>
      <% end %>
    </div>
  </div>

  <hr>
  <h2> Information regarding the property </h2>

  <div class="field">
    <p>Is the Insured Property bound by water (lac, stream, river, etc.)?*</p>
    <%= f.radio_button :bound_water, true, required: true %> YES
    <%= f.radio_button :bound_water, false, required: true %> NO
  </div>

  <div class="field">
    <p>Is the Insured Property on Municipal Water and Municipal Sewer?*</p>
    <%= f.radio_button :muncipal_water, true, required: true %> YES
    <%= f.radio_button :muncipal_water, false, required: true %> NO
  </div>

  <div class="field">
    <p>Has a title insurance already been issued for the insured property according to the client ?*</p>
    <%= f.radio_button :insurance_issued, true, required: true %> YES
    <%= f.radio_button :insurance_issued, false, required: true %> NO
  </div>

  <div class="field">
    <p>Has a title insurance been denied for the insured property, to the best of the client's knowledge?*</p>
    <%= f.radio_button :insurance_denied, true, required: true %> YES
    <%= f.radio_button :insurance_denied, false, required: true %> NO
  </div>

  <hr>
  <div class="field" >
    <h2>Notes</h2>
    <%= f.text_area :note, rows: 5, cols: 100 %>
  </div>

  <div class="field">
    <%= f.label :agent_name %>
    <%= f.text_field :agent_name %>
  </div>
  
  <div class="field">
    <%= f.label :agent_email %>
    <%= f.email_field :agent_email %>
  </div>

  <%= f.submit "Pay Online", class: 'btn btn-success my-3', name: 'pay_online' %>
  <%= f.submit "Get a callback", class: 'btn btn-primary my-3', name: 'request_callback' %>

<% end %>

app/views/quotations/create.js.erb
<% if @quotation.valid? %>
  $("#transaction_form").html("<%= escape_javascript(render partial: 'transaction_form' ) %>");
<% else %>
  $("#error_fields").html("<%= escape_javascript(render partial: 'error' ) %>");
  $(window).scrollTop(0);
<% end %>

app/views/quotations/create_transaction.js.erb
<% if @transaction.valid? %>
  <% if @res_type == 'Callback'%>
    $("#modal_form").html("<%= escape_javascript(render partial: 'callback_modal' ) %>");
    var myModal = new bootstrap.Modal(document.getElementById('callback_form'))
    myModal.show();
  <% else %>
    $("#modal_form").html("<%= escape_javascript(render partial: 'payment_modal' ) %>");
    var myModal = new bootstrap.Modal(document.getElementById('card_info_form'))
    myModal.show();
    $('#card_information_card_number').on('keypress change', function () {
      $(this).val(function (index, value) {
        return value.replace(/\W/gi, '').replace(/(.{4})/g, '$1 ');
      });
    });
  <% end %>
<% else %>
  $("#error_fields").html("<%= escape_javascript(render partial: 'error' ) %>");
  $(window).scrollTop(0);
<% end %>

app/views/quotations/new.html.erb
<h2>Quotation Form</h2>

<%= render 'form', quotation: @quotation %>

app/views/quotations/thank_you.html.erb
<div class="alert alert-success" role="alert">
  Data Saved Successfully
</div>

<h2>Quotation Details</h2>

<table>
  <tbody>
    <tr>
      <td>Name</td>
      <td><%= @quotation.first_name %> <%= @quotation.last_name %></td>
    </tr>
    <tr>
      <td>Phone Number</td>
      <td><%= @quotation.phone_number %> </td>
    </tr>
    <tr>
      <td>Email</td>
      <td><%= @quotation.email %> </td>
    </tr>
    <tr>
      <td>Address</td>
      <td><%= @quotation.address.address %> </td>
    </tr>
    <tr>
      <td>City</td>
      <td><%= @quotation.address.city %> </td>
    </tr>
    <tr>
      <td>Province</td>
      <td><%= @quotation.address.province %> </td>
    </tr>
    <tr>
      <td>Postal Code</td>
      <td><%= @quotation.address.postal_code %> </td>
    </tr>
    <tr>
      <td>Muncipal evaluation of the property</td>
      <td><%= @quotation.eval_value %>$ </td>
    </tr>
    <tr>
      <td>INSURANCE PREMIUM</td>
      <td><%= @quotation.insurance_value %>$ </td>
    </tr>
  </tbody>
</table>

<h2>Transaction Details</h2>
<% @transaction = @quotation.transaction_info.last %>
<table>
  <tbody>
    <tr>
      <td>Languages</td>
      <td><%= TransactionInfo.languages.keys[@transaction.language].titleize %></td>
    </tr>
    <tr>
      <td>Home Owner</td>
      <td><%= @transaction.home_owner_1 %> </td>
    </tr>
    <% if @transaction.home_owner_2? %>
      <tr>
        <td>Home Owner 2</td>
        <td><%= @transaction.home_owner_2 %> </td>
      </tr>
    <%end%>
    <% if @transaction.home_owner_3? %>
      <tr>
        <td>Home Owner 3</td>
        <td><%= @transaction.home_owner_3 %> </td>
      </tr>
    <%end%>
    <tr>
      <td>Property Type</td>
      <td><%= TransactionInfo.property_types.keys[@transaction.property_type] %> </td>
    </tr>
    <tr>
      <td>Property Owner</td>
      <td><%= @transaction.property_owner.humanize %> </td>
    </tr>
    <tr>
      <td>Purchase Date</td>
      <td><%= @transaction.purchase_date %> </td>
    </tr>
    <tr>
      <td>Lot Number</td>
      <td><%= @transaction.lot_number %> </td>
    </tr>
  </tbody>
</table>

<h2>Legal Info</h2>

<table>
  <tbody>
    <tr>
      <td>Lot Number</td>
      <td><%= @transaction.lot_number %> </td>
    </tr>
    <tr>
      <td>Address</td>
      <td><%= @transaction.address.address %> </td>
    </tr>
    <tr>
      <td>City</td>
      <td><%= @transaction.address.city %> </td>
    </tr>
    <tr>
      <td>Province</td>
      <td><%= @transaction.address.province %> </td>
    </tr>
    <tr>
      <td>Postal Code</td>
      <td><%= @transaction.address.postal_code %> </td>
    </tr>
    <tr>
  </tbody>
</table>

<h2>Information regarding property</h2>

<table>
  <tbody>
    <tr>
      <td>Is the Insured Property bound by water (lac, stream, river, etc.)?</td>
      <td><%= @transaction.bound_water.humanize %> </td>
    </tr>
    <tr>
      <td>Is the Insured Property on Municipal Water and Municipal Sewer?</td>
      <td><%= @transaction.muncipal_water.humanize %> </td>
    </tr>
    <tr>
      <td>Has a title insurance already been issued for the insured property according to the client ?</td>
      <td><%= @transaction.insurance_issued.humanize %> </td>
    </tr>
    <tr>
      <td>Has a title insurance been denied for the insured property, to the best of the client's knowledge?</td>
      <td><%= @transaction.insurance_denied.humanize %> </td>
    </tr>
  </tbody>
</table>

<h2>Note</h2>

<table>
  <tbody>
    <tr>
      <td>Note</td>
      <td><%= @transaction.note %> </td>
    </tr>
    <tr>
      <td>Agent Name</td>
      <td><%= @transaction.agent_name %> </td>
    </tr>
    <tr>
      <td>Agen Email</td>
      <td><%= @transaction.agent_email %> </td>
    </tr>
  </tbody>
</table>

<% if @transaction.callback_information.present? %>
  <h3> Callback Requested </h3>
  <div>
  Phone Number:
  <%= @transaction.callback_information.phone_number %>
  </div>
  <div>
  Call Availability:
  <%= CallbackInformation.call_availabilities.keys[@transaction.callback_information.call_availability] %>
  </div>
<% else %>
  <h3 class="text-success my-2"> Payment Done Online </h3>
  <strong> Transaction id:</strong>
  <%= Digest::SHA1.hexdigest(@transaction.card_information.id.to_s)%>
<% end %>
<div> <%= link_to "Done", root_path, class: 'btn btn-primary'%> </div>